#!/usr/bin/env bash

[ -z "$PRIZEM_POSTGRES_NAME" ] && export PRIZEM_POSTGRES_NAME="discovery"
[ -z "$PRIZEM_POSTGRES_HOST" ] && export PRIZEM_POSTGRES_HOST="127.0.0.1"
[ -z "$PRIZEM_POSTGRES_PORT" ] && export PRIZEM_POSTGRES_PORT="5432"
[ -z "$PRIZEM_POSTGRES_USER" ] && export PRIZEM_POSTGRES_USER="discovery"
[ -z "$PRIZEM_POSTGRES_PASSWORD" ] && export PRIZEM_POSTGRES_PASSWORD="discovery"
[ -z "$PRIZEM_EXISTING_POSTGRES_USER" ] && export PRIZEM_EXISTING_POSTGRES_USER="postgres"
[ -z "$PRIZEM_EXISTING_POSTGRES_PASSWORD" ] && export PRIZEM_EXISTING_POSTGRES_PASSWORD=""
[ -z "$PRIZEM_EXISTING_POSTGRES_DATABASE" ] && export PRIZEM_EXISTING_POSTGRES_DATABASE="postgres"