#!/usr/bin/env bash

source ./migrate/defaults.sh

export PGHOST=${PRIZEM_POSTGRES_HOST}
export PGPORT=${PRIZEM_POSTGRES_PORT}
export PGPASSWORD=${PRIZEM_EXISTING_POSTGRES_PASSWORD}
export PGUSER=${PRIZEM_EXISTING_POSTGRES_USER}
export PGDATABASE=${PRIZEM_EXISTING_POSTGRES_DATABASE}

psql -c "CREATE ROLE ${PRIZEM_POSTGRES_USER} WITH LOGIN PASSWORD '${PRIZEM_POSTGRES_PASSWORD}';"
psql -c "ALTER ROLE ${PRIZEM_POSTGRES_USER} CREATEDB;"

export PGPASSWORD=${PRIZEM_POSTGRES_PASSWORD}
export PGUSER=${PRIZEM_POSTGRES_USER}

createdb --owner=${PRIZEM_POSTGRES_USER} ${PRIZEM_POSTGRES_NAME}

./migrate/up.sh